### ISSUE TITLE
No corresponding tag for release 0.1.1

### ISSUE THREAD

**Issue by brlin-tw** [nomeata/ipatch#1]
![screenshot](https://user-images.githubusercontent.com/13408130/157585452-529b01b2-ef17-41df-bb6d-5ffee2673241.png)

I am interested in packaging this application, however, the git tag for 0.1.1 is missing, and hardcoding the commit in the packaging recipe isn't ideal, please add one.

Thanks.

**Comment by nomeata** [comment]
Are you sure you want this? It's a pretty old project, unused and probably bitrotted…

If anything it needs a new maintainer, not just a packager

**Comment by brlin-tw** [comment]
> Are you sure you want this?

I'm looking for selective command-line patch hunk editing experience like `git add --patch`(but without Git).  If there are no better options then yes, I am interested.

> If anything it needs a new maintainer, not just a packager

I agree, unfortunately, I'm not acquainted with Haskell and thus can't take the role even if I'm willing to.

**Comment by nomeata** [comment]
Ok, if it is useful for you, then of course great :)

Pushed a tag.
